# Generated by Django 5.1 on 2024-08-31 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_duration', models.IntegerField()),
                ('event_guest', models.CharField(max_length=255)),
                ('event_participation_count', models.IntegerField(null=True)),
                ('event_cost', models.IntegerField(null=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_winner_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image_location', models.ImageField(blank=True, null=True, upload_to='event/static')),
                ('event_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event_table')),
            ],
        ),
    ]
